general:
  vulnerabilities:
    - CVE-2021-33574
    - CVE-2021-33560
    - CVE-2020-16156
  bestPracticeViolations:
    - CIS-DI-0001
    - DKL-DI-0006
    - CIS-DI-0005
    - CIS-DI-0006
    - CIS-DI-0008