name: App_service

on:
  # Trigger the workflow on push or pull request,
  ## but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [run_my_workflow]

permissions:
  id-token: write
  contents: read

env:
  resourceGroupName: appservicekorea
  acrName: jpWebGithubacr
  appserviceName: jpWebGithub
  COMMIT_REF: $(git rev-parse --short "$GITHUB_SHA")
  GITHUB_FEED: https://nuget.pkg.github.com/junparkorg/junparkLearn/
  GITHUB_USER: junpark12
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  Build-Test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - run: echo "Payload ${{ github.event.client_payload.mydata }}"
      - run: echo "event---${{ github.event_name }} branch---${{ github.ref }}"
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Restore
        run: dotnet restore
#        working-directory: ./WebApp

      - name: Build
        run: dotnet build --configuration Release --no-restore
#        working-directory: ./WebApp
    
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./App6

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ./App6
      

  ARM-Deploy:
    uses: junparkorg/junparkLearn/.github/workflows/Armdeploy.yml@main
    if: contains(github.event.pull_request.labels.*.name, 'armupdate')
    with:
      env_name: 'dev'
      rg_name: 'appservicekorea'

    secrets:
      az_clidential: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
    

  Deploy-App:
    uses: junparkorg/junparkLearn/.github/workflows/Appdeploy.yml@main
    if: ${{ always() }}
    needs: [Build-Test,ARM-Deploy]
    with:
      env_name: 'dev'
      rg_name: 'appservicekorea'
      acr_name: 'jpWebGithubacr'
      img_tag: $(git rev-parse --short "$GITHUB_SHA")
      appsvc_name: 'jpWebGithub'

    secrets:
      az_clidential: ${{ secrets.AZURE_CREDENTIALS }}
      reg_username: ${{ secrets.REGISTRY_USERNAME }}
      reg_password: ${{ secrets.REGISTRY_PASSWORD }}     


  Deploy-Prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [Deploy-App]
    if: always() && needs.Deploy-App.result == 'success'
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'https://jpwebgithub.azurewebsites.net'
          allow_issue_writing: true
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}
      