name: App_service

on:
  # Trigger the workflow on push or pull request,
  ## but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  resourceGroupName: appservicekorea
  acrName: jpWebGithubacr
  appserviceName: jpWebGithub
  COMMIT_REF: $(git rev-parse --short "$GITHUB_SHA")
  GITHUB_FEED: https://nuget.pkg.github.com/junparkorg/junparkLearn/
  GITHUB_USER: junpark12
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  Build-Test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
        

    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - run: echo "event-${{ github.event_name }} branch-${{ github.ref }}"
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Restore
        run: dotnet restore
#        working-directory: ./WebApp

      - name: Build
        run: dotnet build --configuration Release --no-restore
#        working-directory: ./WebApp
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal


  ARM-Deploy:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    if: contains(github.event.pull_request.labels.*.name, 'armupdate')
    steps:
      #login to azure
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      #create resource group
      - name: Create Resource Group
        run: |
          az group create -g "${{ env.resourceGroupName }}" -l "Korea Central"

      #Deploy Arm Template 
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./Infrastructure/main.json
          deploymentMode: Incremental

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
              az logout
              az cache purge
              az account clear

  Deploy-Dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    if: ${{ always() }}
    needs: [Build-Test,ARM-Deploy]
    steps:
      #login to azure
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build image with ACR
        run: |
            az acr build --registry ${{ env.acrName }} --image aspnet6webapp:${{ env.COMMIT_REF }} ./App6/
            az acr import --name ${{ env.acrName }} --source ${{ env.acrName }}.azurecr.io/aspnet6webapp:${{ env.COMMIT_REF }} --image aspnet6webapp:latest --force
      
      #scan image
      - uses: azure/container-scan@v0
        with:
          image-name: ${{ env.acrName }}.azurecr.io/aspnet6webapp:latest
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy the image to App Service
        run: |
            az webapp config container set --name ${{ env.appserviceName }} --resource-group ${{ env.resourceGroupName }} --docker-custom-image-name "${{ env.acrName }}.azurecr.io/aspnet6webapp:${{ env.COMMIT_REF }}" --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az logout
              az cache purge
              az account clear     


  Deploy-Prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [Build-Test,Deploy-Dev]
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}