name: App_service

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  resourceGroupName: githubkorea
  bicepfilePath: ./Infrastructure/main.bicep

jobs:
  Build:
    runs-on: ubuntu-20.04

    env:
      COMMIT_REF: $(git rev-parse --short "$GITHUB_SHA")

    steps:
      - uses: actions/checkout@v2      

      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      #create resource group
      - name: Create Resource Group
        run: |
          az group create -g "${{ env.resourceGroupName }}" -l "Korea Central"

      #Deploy Arm Template 
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./Infrastructure/main.json
          deploymentMode: Incremental

      - name: Build image with ACR
        run: |
          az acr build --registry ${{ steps.deploy.outputs.registryNameOutput }} --image aspnet5webapp:${{ env.COMMIT_REF }} ./WebApp/
      - name: Deploy the image to App Service
        run: |
          az webapp config container set --name ${{ steps.deploy.outputs.webAppNameOutput }} --resource-group ${{ steps.deploy.outputs.resourceGroupOutput }} --docker-custom-image-name aspnet5webapp:${{ env.COMMIT_REF }} --docker-registry-server-url https://${{ steps.deploy.outputs.registryNameOutput }}.azurecr.io --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}


      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
              az logout
              az cache purge
              az account clear